### ISSUE TITLE
Error on Forms Settings page when API key not found

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-gravity-forms#16]
When the CK API key is blank
![settings convertkit wordpress 2018-05-02 12-24-53](https://user-images.githubusercontent.com/290886/39538880-d48e5a2a-4e03-11e8-9bbb-c1ac6d877c37.png)

then the site admin goes to a Form > Settings > ConvertKit > Add there is a fatal error:

```
[02-May-2018 17:27:53 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /Users/daniel/code/convertkit/convertkit-gravity-forms/components/gravityforms/class-gf-convertkit.php:278
Stack trace:
#0 /Users/daniel/code/convertkit/convertkit-gravity-forms/components/gravityforms/class-gf-convertkit.php(136): GFConvertKit->get_custom_fields()
#1 /Users/daniel/sites/convertkit/wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(1294): GFConvertKit->feed_settings_fields()
#2 /Users/daniel/sites/convertkit/wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(1096): GFFeedAddOn->get_feed_settings_fields(Array)
#3 /Users/daniel/sites/convertkit/wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(1041): GFFeedAddOn->feed_edit_page(Array, '0')
#4 /Users/daniel/sites/convertkit/wp-content/plugins/gravityforms/includes/addon/class-gf-addon.php(4190): GFFeedAddOn->form_settings(Array)
#5 /Users/daniel/sites/convertkit/wp-includes/class-wp-hook.php(286): GFAddOn->form_settings_pag in /Users/daniel/code/convertkit/convertkit-gravity-forms/components/gravityforms/class-gf-convertkit.php on line 278

```

**Comment by tnorthcutt** [comment]
Will be closed in https://github.com/ConvertKit/convertkit-gravity-forms/pull/24
